# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synapticview1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from activations import Sigmoid

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *

from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui 

activationslist = ["",
                   "Tanh",
                   "ReLU",
                   "Sigmoid",
                   "Softmax_CrossEntropy",
                   "Softmax"]

lossfunclist = ["",
                "mean_square_error",
                "cross_entropy_loss",
                "",]

comboboxcolor = "QComboBox""{""background-color: #5b5b5b;""}"



class Ui_MainWindow(object):
    
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 869)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(91, 91, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(61, 61, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        
        #### Main ####
        MainWindow.setPalette(palette)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        
        
        #### Central ####
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #### Network definition ####
        self.network_frame = QtWidgets.QFrame(self.centralwidget)
        self.network_frame.setGeometry(QtCore.QRect(30, 110, 351, 691))
        self.network_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.network_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.network_frame.setLineWidth(2)
        self.network_frame.setObjectName("network_frame")
        self.label = QtWidgets.QLabel(self.network_frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label.setObjectName("label")
        
        ## Buttons Network ##
        self.pushButton_ntcreate = QtWidgets.QPushButton(self.network_frame)
        self.pushButton_ntcreate.setGeometry(QtCore.QRect(10, 650, 181, 31))
        self.pushButton_ntcreate.setObjectName("pushButton_ntcreate")
        #self.pushButton_ntcreate.clicked.connect(self.networkexporter)
        
        self.pushButton_ntclean = QtWidgets.QPushButton(self.network_frame)
        self.pushButton_ntclean.setGeometry(QtCore.QRect(190, 650, 151, 31))
        self.pushButton_ntclean.setObjectName("pushButton_ntclean")
        
        
        
        
        ## Neuron 1 ##
        self.frame_neuron1 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron1.setGeometry(QtCore.QRect(10, 30, 331, 71))
        self.frame_neuron1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron1.setObjectName("frame_neuron1")
        
        self.pushButton_n1 = QtWidgets.QPushButton(self.frame_neuron1)
        self.pushButton_n1.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n1.setObjectName("pushButton_n1")
        
        self.spinBox_n1 = QtWidgets.QSpinBox(self.frame_neuron1)
        self.spinBox_n1.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n1.setObjectName("spinBox_n1")
        
        self.comboBox_n1 = QtWidgets.QComboBox(self.frame_neuron1)
        self.comboBox_n1.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n1.setObjectName("comboBox_n1")
        self.comboBox_n1.addItems(activationslist)
        self.comboBox_n1.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n1 = QtWidgets.QLineEdit(self.frame_neuron1)
        self.lineEdit_n1.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n1.setObjectName("lineEdit_n1")
        
        self.checkBox_n1 = QtWidgets.QCheckBox(self.frame_neuron1)
        self.checkBox_n1.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n1.setObjectName("checkBox_n1")
        self.checkBox_n1.stateChanged.connect(self.chbox_n1)
        
        
        
        self.checkBox_conv_1 = QtWidgets.QCheckBox(self.frame_neuron1)
        self.checkBox_conv_1.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_1.setObjectName("checkBox_conv_1")
        
        self.checkBox_nkernell_1 = QtWidgets.QCheckBox(self.frame_neuron1)
        self.checkBox_nkernell_1.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_1.setObjectName("checkBox_nkernell_1")
        
        
        
        
                
        ## Neuron 2 ##
        self.frame_neuron2 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron2.setGeometry(QtCore.QRect(10, 100, 331, 71))
        self.frame_neuron2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron2.setObjectName("frame_neuron2")
        self.frame_neuron2.setEnabled(False)
        
        self.pushButton_n2 = QtWidgets.QPushButton(self.frame_neuron2)
        self.pushButton_n2.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n2.setObjectName("pushButton_n2")
        
        self.spinBox_n2 = QtWidgets.QSpinBox(self.frame_neuron2)
        self.spinBox_n2.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n2.setObjectName("spinBox_n2")
        
        self.comboBox_n2 = QtWidgets.QComboBox(self.frame_neuron2)
        self.comboBox_n2.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n2.setObjectName("comboBox_n2")
        self.comboBox_n2.addItems(activationslist)
        self.comboBox_n2.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n2 = QtWidgets.QLineEdit(self.frame_neuron2)
        self.lineEdit_n2.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n2.setObjectName("lineEdit_n2")
        
        self.checkBox_n2 = QtWidgets.QCheckBox(self.frame_neuron2)
        self.checkBox_n2.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n2.setObjectName("checkBox_n2")
        self.checkBox_n2.stateChanged.connect(self.chbox_n2)
        
        self.checkBox_nkernell_2 = QtWidgets.QCheckBox(self.frame_neuron2)
        self.checkBox_nkernell_2.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_2.setObjectName("checkBox_nkernell_2")
        
        self.checkBox_conv_2 = QtWidgets.QCheckBox(self.frame_neuron2)
        self.checkBox_conv_2.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_2.setObjectName("checkBox_conv_2")
        
        
        ## Neuron 3 ##
        self.frame_neuron3 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron3.setGeometry(QtCore.QRect(10, 170, 331, 71))
        self.frame_neuron3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron3.setObjectName("frame_neuron3")
        self.frame_neuron3.setEnabled(False)
        
        self.pushButton_n3 = QtWidgets.QPushButton(self.frame_neuron3)
        self.pushButton_n3.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n3.setObjectName("pushButton_n3")
        
        self.spinBox_n3 = QtWidgets.QSpinBox(self.frame_neuron3)
        self.spinBox_n3.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n3.setObjectName("spinBox_n3")
        
        self.comboBox_n3 = QtWidgets.QComboBox(self.frame_neuron3)
        self.comboBox_n3.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n3.setObjectName("comboBox_n3")
        self.comboBox_n3.addItems(activationslist)
        self.comboBox_n3.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n3 = QtWidgets.QLineEdit(self.frame_neuron3)
        self.lineEdit_n3.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n3.setObjectName("lineEdit_n3")
        
        self.checkBox_n3 = QtWidgets.QCheckBox(self.frame_neuron3)
        self.checkBox_n3.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n3.setObjectName("checkBox_n3")
        self.checkBox_n3.stateChanged.connect(self.chbox_n3)
        
        self.checkBox_nkernell_3 = QtWidgets.QCheckBox(self.frame_neuron3)
        self.checkBox_nkernell_3.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_3.setObjectName("checkBox_nkernell_3")
        
        self.checkBox_conv_3 = QtWidgets.QCheckBox(self.frame_neuron3)
        self.checkBox_conv_3.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_3.setObjectName("checkBox_conv_3")
        
        ## Neuron 4 ##
        self.frame_neuron4 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron4.setGeometry(QtCore.QRect(10, 240, 331, 71))
        self.frame_neuron4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron4.setObjectName("frame_neuron4")
        self.frame_neuron4.setEnabled(False)
        
        self.pushButton_n4 = QtWidgets.QPushButton(self.frame_neuron4)
        self.pushButton_n4.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n4.setObjectName("pushButton_n4")
        
        self.spinBox_n4 = QtWidgets.QSpinBox(self.frame_neuron4)
        self.spinBox_n4.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n4.setObjectName("spinBox_n4")
        
        self.comboBox_n4 = QtWidgets.QComboBox(self.frame_neuron4)
        self.comboBox_n4.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n4.setObjectName("comboBox_n4")
        self.comboBox_n4.addItems(activationslist)
        self.comboBox_n4.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n4 = QtWidgets.QLineEdit(self.frame_neuron4)
        self.lineEdit_n4.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n4.setObjectName("lineEdit_n4")
        
        self.checkBox_n4 = QtWidgets.QCheckBox(self.frame_neuron4)
        self.checkBox_n4.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n4.setObjectName("checkBox_n4")
        self.checkBox_n4.stateChanged.connect(self.chbox_n4)
        
        
        self.checkBox_nkernell_4 = QtWidgets.QCheckBox(self.frame_neuron4)
        self.checkBox_nkernell_4.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_4.setObjectName("checkBox_nkernell_4")
        
        self.checkBox_conv_4 = QtWidgets.QCheckBox(self.frame_neuron4)
        self.checkBox_conv_4.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_4.setObjectName("checkBox_conv_4")
        
        
        ## Neuron 5 ##
        self.frame_neuron5 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron5.setGeometry(QtCore.QRect(10, 310, 331, 71))
        self.frame_neuron5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron5.setObjectName("frame_neuron5")
        self.frame_neuron5.setEnabled(False)
        
        
        self.pushButton_n5 = QtWidgets.QPushButton(self.frame_neuron5)
        self.pushButton_n5.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n5.setObjectName("pushButton_n5")
        
        self.spinBox_n5 = QtWidgets.QSpinBox(self.frame_neuron5)
        self.spinBox_n5.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n5.setObjectName("spinBox_n5")
        
        self.comboBox_n5 = QtWidgets.QComboBox(self.frame_neuron5)
        self.comboBox_n5.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n5.setObjectName("comboBox_n5")
        self.comboBox_n5.addItems(activationslist)
        self.comboBox_n5.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n5 = QtWidgets.QLineEdit(self.frame_neuron5)
        self.lineEdit_n5.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n5.setObjectName("lineEdit_n5")
        
        self.checkBox_n5 = QtWidgets.QCheckBox(self.frame_neuron5)
        self.checkBox_n5.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n5.setObjectName("checkBox_n5")
        self.checkBox_n5.stateChanged.connect(self.chbox_n5)
        
        self.checkBox_nkernell_5 = QtWidgets.QCheckBox(self.frame_neuron5)
        self.checkBox_nkernell_5.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_5.setObjectName("checkBox_nkernell_5")
        
        self.checkBox_conv_5 = QtWidgets.QCheckBox(self.frame_neuron5)
        self.checkBox_conv_5.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_5.setObjectName("checkBox_conv_5")
        
        ## Neuron 6 ##
        self.frame_neuron6 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron6.setGeometry(QtCore.QRect(10, 380, 331, 71))
        self.frame_neuron6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron6.setObjectName("frame_neuron6")
        self.frame_neuron6.setEnabled(False)
        
        
        self.pushButton_n6 = QtWidgets.QPushButton(self.frame_neuron6)
        self.pushButton_n6.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n6.setObjectName("pushButton_n6")
        
        self.spinBox_n6 = QtWidgets.QSpinBox(self.frame_neuron6)
        self.spinBox_n6.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n6.setObjectName("spinBox_n6")
        
        self.comboBox_n6 = QtWidgets.QComboBox(self.frame_neuron6)
        self.comboBox_n6.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n6.setObjectName("comboBox_n6")
        self.comboBox_n6.addItems(activationslist)
        self.comboBox_n6.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n6 = QtWidgets.QLineEdit(self.frame_neuron6)
        self.lineEdit_n6.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n6.setObjectName("lineEdit_n6")
        
        self.checkBox_n6 = QtWidgets.QCheckBox(self.frame_neuron6)
        self.checkBox_n6.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n6.setObjectName("checkBox_n6")
        self.checkBox_n6.stateChanged.connect(self.chbox_n6)
        
        self.checkBox_nkernell_6 = QtWidgets.QCheckBox(self.frame_neuron6)
        self.checkBox_nkernell_6.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_6.setObjectName("checkBox_nkernell_6")
        
        self.checkBox_conv_6 = QtWidgets.QCheckBox(self.frame_neuron6)
        self.checkBox_conv_6.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_6.setObjectName("checkBox_conv_6")
        
        ## Neuron 7 ##
        self.frame_neuron7 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron7.setGeometry(QtCore.QRect(10, 450, 331, 71))
        self.frame_neuron7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron7.setObjectName("frame_neuron7")
        self.frame_neuron7.setEnabled(False)
        
        
        self.pushButton_n7 = QtWidgets.QPushButton(self.frame_neuron7)
        self.pushButton_n7.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n7.setObjectName("pushButton_n7")
        
        self.spinBox_n7 = QtWidgets.QSpinBox(self.frame_neuron7)
        self.spinBox_n7.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n7.setObjectName("spinBox_n7")
        
        self.comboBox_n7 = QtWidgets.QComboBox(self.frame_neuron7)
        self.comboBox_n7.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n7.setObjectName("comboBox_n7")
        self.comboBox_n7.addItems(activationslist)
        self.comboBox_n7.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n7 = QtWidgets.QLineEdit(self.frame_neuron7)
        self.lineEdit_n7.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n7.setObjectName("lineEdit_n7")
        
        self.checkBox_n7 = QtWidgets.QCheckBox(self.frame_neuron7)
        self.checkBox_n7.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n7.setObjectName("checkBox_n7")
        self.checkBox_n7.stateChanged.connect(self.chbox_n7)
        
        self.checkBox_nkernell_7 = QtWidgets.QCheckBox(self.frame_neuron7)
        self.checkBox_nkernell_7.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_7.setObjectName("checkBox_nkernell_7")
        
        self.checkBox_conv_7 = QtWidgets.QCheckBox(self.frame_neuron7)
        self.checkBox_conv_7.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_7.setObjectName("checkBox_conv_7")
        
        ## Neuron 8 ##
        self.frame_neuron8 = QtWidgets.QFrame(self.network_frame)
        self.frame_neuron8.setEnabled(False)
        self.frame_neuron8.setGeometry(QtCore.QRect(10, 520, 331, 71))
        self.frame_neuron8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_neuron8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_neuron8.setObjectName("frame_neuron8")
        
        self.pushButton_n8 = QtWidgets.QPushButton(self.frame_neuron8)
        self.pushButton_n8.setGeometry(QtCore.QRect(300, 40, 21, 21))
        self.pushButton_n8.setObjectName("pushButton_n8")
        
        self.spinBox_n8 = QtWidgets.QSpinBox(self.frame_neuron8)
        self.spinBox_n8.setGeometry(QtCore.QRect(120, 10, 61, 22))
        self.spinBox_n8.setObjectName("spinBox_n8")
        
        self.comboBox_n8 = QtWidgets.QComboBox(self.frame_neuron8)
        self.comboBox_n8.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.comboBox_n8.setObjectName("comboBox_n8")
        self.comboBox_n8.addItems(activationslist)
        self.comboBox_n8.setStyleSheet(comboboxcolor) 
        
        self.lineEdit_n8 = QtWidgets.QLineEdit(self.frame_neuron8)
        self.lineEdit_n8.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.lineEdit_n8.setObjectName("lineEdit_n8")
        
        self.checkBox_n8 = QtWidgets.QCheckBox(self.frame_neuron8)
        self.checkBox_n8.setGeometry(QtCore.QRect(230, 40, 61, 17))
        self.checkBox_n8.setObjectName("checkBox_n8")
        
        self.checkBox_nkernell_8 = QtWidgets.QCheckBox(self.frame_neuron8)
        self.checkBox_nkernell_8.setGeometry(QtCore.QRect(260, 10, 70, 17))
        self.checkBox_nkernell_8.setObjectName("checkBox_nkernell_8")
        
        self.checkBox_conv_8 = QtWidgets.QCheckBox(self.frame_neuron8)
        self.checkBox_conv_8.setGeometry(QtCore.QRect(190, 10, 70, 17))
        self.checkBox_conv_8.setObjectName("checkBox_conv_8")
        
        
        ## Loss ##
        self.frame_loss = QtWidgets.QFrame(self.network_frame)
        self.frame_loss.setGeometry(QtCore.QRect(10, 590, 331, 61))
        self.frame_loss.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_loss.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_loss.setLineWidth(2)
        self.frame_loss.setObjectName("frame_loss")
        
        self.loss_label = QtWidgets.QLabel(self.frame_loss)
        self.loss_label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.loss_label.setObjectName("loss_label")
        
        self.comboBox = QtWidgets.QComboBox(self.frame_loss)
        self.comboBox.setGeometry(QtCore.QRect(100, 20, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(lossfunclist)
        self.comboBox.setStyleSheet(comboboxcolor) 
        
        
        
        self.listofneurons = [self.frame_neuron1,
                              self.frame_neuron2,
                              self.frame_neuron3,
                              self.frame_neuron4,
                              self.frame_neuron5,
                              self.frame_neuron6,
                              self.frame_neuron7,
                              self.frame_neuron8,]
        
        self.listofchecks = [self.checkBox_n1,
                             self.checkBox_n2,
                             self.checkBox_n3,
                             self.checkBox_n4,
                             self.checkBox_n5,
                             self.checkBox_n6,
                             self.checkBox_n7,
                             self.checkBox_n8,]
        
        self.listofnumbers = [self.spinBox_n1,
                              self.spinBox_n2,
                              self.spinBox_n3,
                              self.spinBox_n4,
                              self.spinBox_n5,
                              self.spinBox_n6,
                              self.spinBox_n7,
                              self.spinBox_n8,]
        
        self.activlist = [self.comboBox_n1,
                          self.comboBox_n2,
                          self.comboBox_n3,
                          self.comboBox_n4,
                          self.comboBox_n5,
                          self.comboBox_n6,
                          self.comboBox_n7,
                          self.comboBox_n8,]
        
        #### Training ####
        self.training_frame = QtWidgets.QFrame(self.centralwidget)
        self.training_frame.setGeometry(QtCore.QRect(390, 270, 691, 251))
        self.training_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.training_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.training_frame.setLineWidth(2)
        self.training_frame.setObjectName("training_frame")
        
        self.progressBar_epoch = QtWidgets.QProgressBar(self.training_frame)
        self.progressBar_epoch.setGeometry(QtCore.QRect(30, 110, 641, 23))
        self.progressBar_epoch.setProperty("value", 24)
        self.progressBar_epoch.setObjectName("progressBar_epoch")
        
        self.pushButton = QtWidgets.QPushButton(self.training_frame)
        self.pushButton.setGeometry(QtCore.QRect(730, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_starttrain = QtWidgets.QPushButton(self.training_frame)
        self.pushButton_starttrain.setGeometry(QtCore.QRect(554, 20, 121, 41))
        self.pushButton_starttrain.setObjectName("pushButton_starttrain")
        
        self.progressBar_batch = QtWidgets.QProgressBar(self.training_frame)
        self.progressBar_batch.setGeometry(QtCore.QRect(30, 180, 641, 23))
        self.progressBar_batch.setProperty("value", 24)
        self.progressBar_batch.setObjectName("progressBar_batch")
        
        self.pushButton_canceltrain = QtWidgets.QPushButton(self.training_frame)
        self.pushButton_canceltrain.setGeometry(QtCore.QRect(600, 220, 75, 23))
        self.pushButton_canceltrain.setObjectName("pushButton_canceltrain")
        
        self.checkBox_testontheway = QtWidgets.QCheckBox(self.training_frame)
        self.checkBox_testontheway.setGeometry(QtCore.QRect(40, 220, 311, 17))
        self.checkBox_testontheway.setObjectName("checkBox_testontheway")
        
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.training_frame)
        self.doubleSpinBox.setGeometry(QtCore.QRect(450, 30, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        
        self.spinBox = QtWidgets.QSpinBox(self.training_frame)
        self.spinBox.setGeometry(QtCore.QRect(120, 30, 71, 22))
        self.spinBox.setObjectName("spinBox")
        
        self.label_epochs = QtWidgets.QLabel(self.training_frame)
        self.label_epochs.setGeometry(QtCore.QRect(69, 30, 47, 13))
        self.label_epochs.setObjectName("label_epochs")
        
        self.label_learnig = QtWidgets.QLabel(self.training_frame)
        self.label_learnig.setGeometry(QtCore.QRect(340, 30, 81, 16))
        self.label_learnig.setObjectName("label_learnig")
        
        self.label_advanceepoch = QtWidgets.QLabel(self.training_frame)
        self.label_advanceepoch.setGeometry(QtCore.QRect(30, 70, 91, 20))
        self.label_advanceepoch.setObjectName("label_advanceepoch")
        
        self.label_advancetraining = QtWidgets.QLabel(self.training_frame)
        self.label_advancetraining.setGeometry(QtCore.QRect(30, 150, 101, 16))
        self.label_advancetraining.setObjectName("label_advancetraining")
        
        
        #### Database ####
        self.database_frame = QtWidgets.QFrame(self.centralwidget)
        self.database_frame.setGeometry(QtCore.QRect(390, 111, 691, 151))
        self.database_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.database_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.database_frame.setLineWidth(2)
        self.database_frame.setObjectName("database_frame")
        
        self.label_4 = QtWidgets.QLabel(self.database_frame)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 301, 16))
        self.label_4.setObjectName("label_4")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.database_frame)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 110, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        
        
        #### Mathplotlib ####
        self.frame_mathplotlib = QtWidgets.QFrame(self.centralwidget)
        self.frame_mathplotlib.setGeometry(QtCore.QRect(820, 530, 261, 271))
        self.frame_mathplotlib.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_mathplotlib.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_mathplotlib.setLineWidth(2)
        self.frame_mathplotlib.setObjectName("frame_mathplotlib")
        self.label_2 = QtWidgets.QLabel(self.frame_mathplotlib)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 201, 16))
        self.label_2.setObjectName("label_2")
        
        
        #### Results ####
        self.frame_results = QtWidgets.QFrame(self.centralwidget)
        self.frame_results.setGeometry(QtCore.QRect(390, 531, 421, 271))
        self.frame_results.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_results.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_results.setLineWidth(2)
        self.frame_results.setObjectName("frame_results")
        self.label_3 = QtWidgets.QLabel(self.frame_results)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 261, 16))
        self.label_3.setObjectName("label_3")
        
                
        
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(30, 20, 1051, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 21))
        """palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)"""
        #self.menubar.setPalette(palette)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Area de definicion de la red"))
        self.pushButton_ntclean.setText(_translate("MainWindow", "PushButton"))
        self.loss_label.setText(_translate("MainWindow", "Loss Function"))
        self.pushButton_n1.setText( "PushButton cancelation of neuron")
        self.lineEdit_n1.setInputMask("neuron")
        self.lineEdit_n1.setText( "neuron")
        self.checkBox_n1.setText("CheckBox")
        self.checkBox_conv_1.setText("CheckBox")
        self.checkBox_nkernell_1.setText("CheckBox")
        self.pushButton_n2.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n2.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n2.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_2.setText(_translate("MainWindow", "CheckBox"))
        
        self.pushButton_n3.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n3.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n3.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_3.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_n4.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n4.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n4.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_4.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_n5.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n5.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n5.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_5.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_n6.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n6.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n6.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_6.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_n7.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n7.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n7.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_7.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_n8.setText(_translate("MainWindow", "PushButton cancelation of neuron"))
        self.lineEdit_n8.setInputMask(_translate("MainWindow", "neuron"))
        self.lineEdit_n8.setText(_translate("MainWindow", "neuron"))
        self.checkBox_n8.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_nkernell_8.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_conv_8.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_ntcreate.setText(_translate("MainWindow", "Create Network"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_starttrain.setText(_translate("MainWindow", "Start Training/Testing"))
        self.pushButton_canceltrain.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_testontheway.setText(_translate("MainWindow", "CheckBox para indicar testeo"))
        self.label_epochs.setText(_translate("MainWindow", "Epochs:"))
        self.label_learnig.setText(_translate("MainWindow", "Learning Rate:"))
        self.label_advanceepoch.setText(_translate("MainWindow", "Advance on Epoch:"))
        self.label_advancetraining.setText(_translate("MainWindow", "Advance on Training:"))
        self.label_4.setText(_translate("MainWindow", "TextLabel carga de databases"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "TextLabel quitar: va matpltlib"))
        self.label_3.setText(_translate("MainWindow", "TextLabel Arrea de resultados"))
        
    
            
        
        
    def chbox_n1(self):
            if self.checkBox_n1.isChecked():
                self.frame_neuron2.setEnabled(True)
            else:
                self.frame_neuron2.setEnabled(False)
                self.frame_neuron3.setEnabled(False)
                self.frame_neuron4.setEnabled(False)
                self.frame_neuron5.setEnabled(False)
                self.frame_neuron6.setEnabled(False)
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
                
                
    def chbox_n2(self):
            if self.checkBox_n2.isChecked():
                self.frame_neuron3.setEnabled(True)
            else:
                self.frame_neuron3.setEnabled(False)
                self.frame_neuron4.setEnabled(False)
                self.frame_neuron5.setEnabled(False)
                self.frame_neuron6.setEnabled(False)
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
    
    def chbox_n3(self):
            if self.checkBox_n3.isChecked():
                self.frame_neuron4.setEnabled(True)
            else:
                self.frame_neuron4.setEnabled(False)
                self.frame_neuron5.setEnabled(False)
                self.frame_neuron6.setEnabled(False)
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
    
    def chbox_n4(self):
            if self.checkBox_n4.isChecked():
                self.frame_neuron5.setEnabled(True)
            else:
                self.frame_neuron5.setEnabled(False)
                self.frame_neuron6.setEnabled(False)
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
    
    def chbox_n5(self):
            if self.checkBox_n5.isChecked():
                self.frame_neuron6.setEnabled(True)
            else:
                self.frame_neuron6.setEnabled(False)
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
    
    def chbox_n6(self):
            if self.checkBox_n6.isChecked():
                self.frame_neuron7.setEnabled(True)
            else:
                self.frame_neuron7.setEnabled(False)
                self.frame_neuron8.setEnabled(False)
    
    def chbox_n7(self):
            if self.checkBox_n7.isChecked():
                self.frame_neuron8.setEnabled(True)
            else:
                self.frame_neuron8.setEnabled(False)
                
        
                
    """ def networkexporter(self):
        activationslistexport = []
        neuronslist = []
        for i in range(len(self.listofneurons)):
            if self.listofneurons[i].isEnabled():
                if self.listofchecks[i].isChecked():
                    if self.activlist[i].currentText() != "":
                        neuronslist.append(int(self.listofnumbers[i].text()))
                        activationslistexport.append(self.activlist[i].currentText())
                    
        return neuronslist, activationslistexport"""
                
                
    
    
        
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
